export const typesConstants = {
  BasePath: Symbol.for('BasePath'),
  WinstonLogger: Symbol.for('WinstonLogger'),
  NodeEnv: Symbol.for('NODE_ENV'),
  DBConnection: Symbol.for('DBConnection'),
  RedisHost: Symbol.for('RedisHost'),
  RedisPort: Symbol.for('RedisPort'),
  JwtSecretKey: Symbol.for('JwtSecretKey'),
  BotUrl: Symbol.for('BotUrl'),
  Socket: Symbol.for('Socket'),
  TranslateKeyFile: Symbol.for('TranslateKeyFile'),
  TranslateProjectId: Symbol.for('TranslateProjectId'),
  Locale: Symbol.for('Locale'),
  DefaultLocale: Symbol.for('DefaultLocale'),
};
