version: '2.4'

services:
  blog-postgres:
    container_name: blog-postgres
    build: ./docker/postgres
    image: blog-postgres
    env_file:
    - .env
    ports:
    - 5432:5432
    volumes:
    - ./docker-data/postgres/data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  blog-redis:
    container_name: blog-redis
    image: redis:5.0-alpine
    restart: always
    ports:
    - 6379:6379
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
